/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticalAchievementsRouteImport } from './routes/political-achievements'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as ImageRouteImport } from './routes/image'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BecomeMemberRouteImport } from './routes/become-member'
import { Route as AssociationEventsRouteImport } from './routes/association-events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CategoriesVehicleSafetyRouteImport } from './routes/categories.vehicle-safety'
import { Route as CategoriesUsedVehicleChecklistRouteImport } from './routes/categories.used-vehicle-checklist'
import { Route as CategoriesTransferOwnershipRouteImport } from './routes/categories.transfer-ownership'
import { Route as CategoriesTransferFeesRouteImport } from './routes/categories.transfer-fees'
import { Route as CategoriesRulesRouteImport } from './routes/categories.rules'
import { Route as CategoriesRtoListRouteImport } from './routes/categories.rto-list'
import { Route as CategoriesOurOfficeRouteImport } from './routes/categories.our-office'
import { Route as CategoriesOtherStateVehicleRouteImport } from './routes/categories.other-state-vehicle'
import { Route as CategoriesObtainNocRouteImport } from './routes/categories.obtain-noc'
import { Route as CategoriesNewsRouteImport } from './routes/categories.news'
import { Route as CategoriesNewVehicleRouteImport } from './routes/categories.new-vehicle'
import { Route as CategoriesNewRegistrationsRouteImport } from './routes/categories.new-registrations'
import { Route as CategoriesInformationOnFormsRouteImport } from './routes/categories.information-on-forms'
import { Route as CategoriesImportantFormsRouteImport } from './routes/categories.important-forms'
import { Route as CategoriesFeesStructureRouteImport } from './routes/categories.fees-structure'
import { Route as CategoriesEmiCalculatorRouteImport } from './routes/categories.emi-calculator'
import { Route as CategoriesDuplicateRcRouteImport } from './routes/categories.duplicate-rc'
import { Route as CategoriesAuthorizedDealersRouteImport } from './routes/categories.authorized-dealers'
import { Route as AdminSuperAdminsRouteImport } from './routes/admin.super-admins'
import { Route as AdminResetManagementRouteImport } from './routes/admin.reset-management'
import { Route as AdminResetDirectoryRouteImport } from './routes/admin.reset-directory'
import { Route as AdminOurStaffRouteImport } from './routes/admin.our-staff'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImportantDatesRouteImport } from './routes/admin.important-dates'
import { Route as AdminImageRouteImport } from './routes/admin.image'
import { Route as AdminExpiredMembersRouteImport } from './routes/admin.expired-members'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminDirectoryRouteImport } from './routes/admin.directory'
import { Route as AdminComplaintRouteImport } from './routes/admin.complaint'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminDirectoryIndexRouteImport } from './routes/admin.directory.index'
import { Route as AdminDirectoryPartenerRouteImport } from './routes/admin.directory.partener'
import { Route as AdminDirectoryCreateRouteImport } from './routes/admin.directory.create'
import { Route as AdminDirectorySlugDetailsRouteImport } from './routes/admin.directory.$slug.details'
import { Route as AdminDirectoryPartnerSlugDetailsRouteImport } from './routes/admin.directory.partner.$slug.details'

const PoliticalAchievementsRoute = PoliticalAchievementsRouteImport.update({
  id: '/political-achievements',
  path: '/political-achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeMemberRoute = BecomeMemberRouteImport.update({
  id: '/become-member',
  path: '/become-member',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationEventsRoute = AssociationEventsRouteImport.update({
  id: '/association-events',
  path: '/association-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CategoriesVehicleSafetyRoute = CategoriesVehicleSafetyRouteImport.update({
  id: '/categories/vehicle-safety',
  path: '/categories/vehicle-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesUsedVehicleChecklistRoute =
  CategoriesUsedVehicleChecklistRouteImport.update({
    id: '/categories/used-vehicle-checklist',
    path: '/categories/used-vehicle-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesTransferOwnershipRoute =
  CategoriesTransferOwnershipRouteImport.update({
    id: '/categories/transfer-ownership',
    path: '/categories/transfer-ownership',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesTransferFeesRoute = CategoriesTransferFeesRouteImport.update({
  id: '/categories/transfer-fees',
  path: '/categories/transfer-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRulesRoute = CategoriesRulesRouteImport.update({
  id: '/categories/rules',
  path: '/categories/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRtoListRoute = CategoriesRtoListRouteImport.update({
  id: '/categories/rto-list',
  path: '/categories/rto-list',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesOurOfficeRoute = CategoriesOurOfficeRouteImport.update({
  id: '/categories/our-office',
  path: '/categories/our-office',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesOtherStateVehicleRoute =
  CategoriesOtherStateVehicleRouteImport.update({
    id: '/categories/other-state-vehicle',
    path: '/categories/other-state-vehicle',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesObtainNocRoute = CategoriesObtainNocRouteImport.update({
  id: '/categories/obtain-noc',
  path: '/categories/obtain-noc',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewsRoute = CategoriesNewsRouteImport.update({
  id: '/categories/news',
  path: '/categories/news',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewVehicleRoute = CategoriesNewVehicleRouteImport.update({
  id: '/categories/new-vehicle',
  path: '/categories/new-vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewRegistrationsRoute =
  CategoriesNewRegistrationsRouteImport.update({
    id: '/categories/new-registrations',
    path: '/categories/new-registrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesInformationOnFormsRoute =
  CategoriesInformationOnFormsRouteImport.update({
    id: '/categories/information-on-forms',
    path: '/categories/information-on-forms',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesImportantFormsRoute =
  CategoriesImportantFormsRouteImport.update({
    id: '/categories/important-forms',
    path: '/categories/important-forms',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesFeesStructureRoute = CategoriesFeesStructureRouteImport.update({
  id: '/categories/fees-structure',
  path: '/categories/fees-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesEmiCalculatorRoute = CategoriesEmiCalculatorRouteImport.update({
  id: '/categories/emi-calculator',
  path: '/categories/emi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesDuplicateRcRoute = CategoriesDuplicateRcRouteImport.update({
  id: '/categories/duplicate-rc',
  path: '/categories/duplicate-rc',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesAuthorizedDealersRoute =
  CategoriesAuthorizedDealersRouteImport.update({
    id: '/categories/authorized-dealers',
    path: '/categories/authorized-dealers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSuperAdminsRoute = AdminSuperAdminsRouteImport.update({
  id: '/super-admins',
  path: '/super-admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetManagementRoute = AdminResetManagementRouteImport.update({
  id: '/reset-management',
  path: '/reset-management',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetDirectoryRoute = AdminResetDirectoryRouteImport.update({
  id: '/reset-directory',
  path: '/reset-directory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOurStaffRoute = AdminOurStaffRouteImport.update({
  id: '/our-staff',
  path: '/our-staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportantDatesRoute = AdminImportantDatesRouteImport.update({
  id: '/important-dates',
  path: '/important-dates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImageRoute = AdminImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpiredMembersRoute = AdminExpiredMembersRouteImport.update({
  id: '/expired-members',
  path: '/expired-members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintRoute = AdminComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDirectoryIndexRoute = AdminDirectoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDirectoryRoute,
} as any)
const AdminDirectoryPartenerRoute = AdminDirectoryPartenerRouteImport.update({
  id: '/partener',
  path: '/partener',
  getParentRoute: () => AdminDirectoryRoute,
} as any)
const AdminDirectoryCreateRoute = AdminDirectoryCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminDirectoryRoute,
} as any)
const AdminDirectorySlugDetailsRoute =
  AdminDirectorySlugDetailsRouteImport.update({
    id: '/$slug/details',
    path: '/$slug/details',
    getParentRoute: () => AdminDirectoryRoute,
  } as any)
const AdminDirectoryPartnerSlugDetailsRoute =
  AdminDirectoryPartnerSlugDetailsRouteImport.update({
    id: '/partner/$slug/details',
    path: '/partner/$slug/details',
    getParentRoute: () => AdminDirectoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/association-events': typeof AssociationEventsRoute
  '/become-member': typeof BecomeMemberRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/image': typeof ImageRoute
  '/letter': typeof LetterRoute
  '/management': typeof ManagementRoute
  '/political-achievements': typeof PoliticalAchievementsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/complaint': typeof AdminComplaintRoute
  '/admin/directory': typeof AdminDirectoryRouteWithChildren
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/expired-members': typeof AdminExpiredMembersRoute
  '/admin/image': typeof AdminImageRoute
  '/admin/important-dates': typeof AdminImportantDatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/our-staff': typeof AdminOurStaffRoute
  '/admin/reset-directory': typeof AdminResetDirectoryRoute
  '/admin/reset-management': typeof AdminResetManagementRoute
  '/admin/super-admins': typeof AdminSuperAdminsRoute
  '/categories/authorized-dealers': typeof CategoriesAuthorizedDealersRoute
  '/categories/duplicate-rc': typeof CategoriesDuplicateRcRoute
  '/categories/emi-calculator': typeof CategoriesEmiCalculatorRoute
  '/categories/fees-structure': typeof CategoriesFeesStructureRoute
  '/categories/important-forms': typeof CategoriesImportantFormsRoute
  '/categories/information-on-forms': typeof CategoriesInformationOnFormsRoute
  '/categories/new-registrations': typeof CategoriesNewRegistrationsRoute
  '/categories/new-vehicle': typeof CategoriesNewVehicleRoute
  '/categories/news': typeof CategoriesNewsRoute
  '/categories/obtain-noc': typeof CategoriesObtainNocRoute
  '/categories/other-state-vehicle': typeof CategoriesOtherStateVehicleRoute
  '/categories/our-office': typeof CategoriesOurOfficeRoute
  '/categories/rto-list': typeof CategoriesRtoListRoute
  '/categories/rules': typeof CategoriesRulesRoute
  '/categories/transfer-fees': typeof CategoriesTransferFeesRoute
  '/categories/transfer-ownership': typeof CategoriesTransferOwnershipRoute
  '/categories/used-vehicle-checklist': typeof CategoriesUsedVehicleChecklistRoute
  '/categories/vehicle-safety': typeof CategoriesVehicleSafetyRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/directory/create': typeof AdminDirectoryCreateRoute
  '/admin/directory/partener': typeof AdminDirectoryPartenerRoute
  '/admin/directory/': typeof AdminDirectoryIndexRoute
  '/admin/directory/$slug/details': typeof AdminDirectorySlugDetailsRoute
  '/admin/directory/partner/$slug/details': typeof AdminDirectoryPartnerSlugDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/association-events': typeof AssociationEventsRoute
  '/become-member': typeof BecomeMemberRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/image': typeof ImageRoute
  '/letter': typeof LetterRoute
  '/management': typeof ManagementRoute
  '/political-achievements': typeof PoliticalAchievementsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/complaint': typeof AdminComplaintRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/expired-members': typeof AdminExpiredMembersRoute
  '/admin/image': typeof AdminImageRoute
  '/admin/important-dates': typeof AdminImportantDatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/our-staff': typeof AdminOurStaffRoute
  '/admin/reset-directory': typeof AdminResetDirectoryRoute
  '/admin/reset-management': typeof AdminResetManagementRoute
  '/admin/super-admins': typeof AdminSuperAdminsRoute
  '/categories/authorized-dealers': typeof CategoriesAuthorizedDealersRoute
  '/categories/duplicate-rc': typeof CategoriesDuplicateRcRoute
  '/categories/emi-calculator': typeof CategoriesEmiCalculatorRoute
  '/categories/fees-structure': typeof CategoriesFeesStructureRoute
  '/categories/important-forms': typeof CategoriesImportantFormsRoute
  '/categories/information-on-forms': typeof CategoriesInformationOnFormsRoute
  '/categories/new-registrations': typeof CategoriesNewRegistrationsRoute
  '/categories/new-vehicle': typeof CategoriesNewVehicleRoute
  '/categories/news': typeof CategoriesNewsRoute
  '/categories/obtain-noc': typeof CategoriesObtainNocRoute
  '/categories/other-state-vehicle': typeof CategoriesOtherStateVehicleRoute
  '/categories/our-office': typeof CategoriesOurOfficeRoute
  '/categories/rto-list': typeof CategoriesRtoListRoute
  '/categories/rules': typeof CategoriesRulesRoute
  '/categories/transfer-fees': typeof CategoriesTransferFeesRoute
  '/categories/transfer-ownership': typeof CategoriesTransferOwnershipRoute
  '/categories/used-vehicle-checklist': typeof CategoriesUsedVehicleChecklistRoute
  '/categories/vehicle-safety': typeof CategoriesVehicleSafetyRoute
  '/admin': typeof AdminIndexRoute
  '/admin/directory/create': typeof AdminDirectoryCreateRoute
  '/admin/directory/partener': typeof AdminDirectoryPartenerRoute
  '/admin/directory': typeof AdminDirectoryIndexRoute
  '/admin/directory/$slug/details': typeof AdminDirectorySlugDetailsRoute
  '/admin/directory/partner/$slug/details': typeof AdminDirectoryPartnerSlugDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/association-events': typeof AssociationEventsRoute
  '/become-member': typeof BecomeMemberRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/image': typeof ImageRoute
  '/letter': typeof LetterRoute
  '/management': typeof ManagementRoute
  '/political-achievements': typeof PoliticalAchievementsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/complaint': typeof AdminComplaintRoute
  '/admin/directory': typeof AdminDirectoryRouteWithChildren
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/expired-members': typeof AdminExpiredMembersRoute
  '/admin/image': typeof AdminImageRoute
  '/admin/important-dates': typeof AdminImportantDatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/our-staff': typeof AdminOurStaffRoute
  '/admin/reset-directory': typeof AdminResetDirectoryRoute
  '/admin/reset-management': typeof AdminResetManagementRoute
  '/admin/super-admins': typeof AdminSuperAdminsRoute
  '/categories/authorized-dealers': typeof CategoriesAuthorizedDealersRoute
  '/categories/duplicate-rc': typeof CategoriesDuplicateRcRoute
  '/categories/emi-calculator': typeof CategoriesEmiCalculatorRoute
  '/categories/fees-structure': typeof CategoriesFeesStructureRoute
  '/categories/important-forms': typeof CategoriesImportantFormsRoute
  '/categories/information-on-forms': typeof CategoriesInformationOnFormsRoute
  '/categories/new-registrations': typeof CategoriesNewRegistrationsRoute
  '/categories/new-vehicle': typeof CategoriesNewVehicleRoute
  '/categories/news': typeof CategoriesNewsRoute
  '/categories/obtain-noc': typeof CategoriesObtainNocRoute
  '/categories/other-state-vehicle': typeof CategoriesOtherStateVehicleRoute
  '/categories/our-office': typeof CategoriesOurOfficeRoute
  '/categories/rto-list': typeof CategoriesRtoListRoute
  '/categories/rules': typeof CategoriesRulesRoute
  '/categories/transfer-fees': typeof CategoriesTransferFeesRoute
  '/categories/transfer-ownership': typeof CategoriesTransferOwnershipRoute
  '/categories/used-vehicle-checklist': typeof CategoriesUsedVehicleChecklistRoute
  '/categories/vehicle-safety': typeof CategoriesVehicleSafetyRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/directory/create': typeof AdminDirectoryCreateRoute
  '/admin/directory/partener': typeof AdminDirectoryPartenerRoute
  '/admin/directory/': typeof AdminDirectoryIndexRoute
  '/admin/directory/$slug/details': typeof AdminDirectorySlugDetailsRoute
  '/admin/directory/partner/$slug/details': typeof AdminDirectoryPartnerSlugDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/association-events'
    | '/become-member'
    | '/contact'
    | '/directory'
    | '/image'
    | '/letter'
    | '/management'
    | '/political-achievements'
    | '/admin/banners'
    | '/admin/complaint'
    | '/admin/directory'
    | '/admin/enquiries'
    | '/admin/expired-members'
    | '/admin/image'
    | '/admin/important-dates'
    | '/admin/login'
    | '/admin/our-staff'
    | '/admin/reset-directory'
    | '/admin/reset-management'
    | '/admin/super-admins'
    | '/categories/authorized-dealers'
    | '/categories/duplicate-rc'
    | '/categories/emi-calculator'
    | '/categories/fees-structure'
    | '/categories/important-forms'
    | '/categories/information-on-forms'
    | '/categories/new-registrations'
    | '/categories/new-vehicle'
    | '/categories/news'
    | '/categories/obtain-noc'
    | '/categories/other-state-vehicle'
    | '/categories/our-office'
    | '/categories/rto-list'
    | '/categories/rules'
    | '/categories/transfer-fees'
    | '/categories/transfer-ownership'
    | '/categories/used-vehicle-checklist'
    | '/categories/vehicle-safety'
    | '/admin/'
    | '/admin/directory/create'
    | '/admin/directory/partener'
    | '/admin/directory/'
    | '/admin/directory/$slug/details'
    | '/admin/directory/partner/$slug/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/association-events'
    | '/become-member'
    | '/contact'
    | '/directory'
    | '/image'
    | '/letter'
    | '/management'
    | '/political-achievements'
    | '/admin/banners'
    | '/admin/complaint'
    | '/admin/enquiries'
    | '/admin/expired-members'
    | '/admin/image'
    | '/admin/important-dates'
    | '/admin/login'
    | '/admin/our-staff'
    | '/admin/reset-directory'
    | '/admin/reset-management'
    | '/admin/super-admins'
    | '/categories/authorized-dealers'
    | '/categories/duplicate-rc'
    | '/categories/emi-calculator'
    | '/categories/fees-structure'
    | '/categories/important-forms'
    | '/categories/information-on-forms'
    | '/categories/new-registrations'
    | '/categories/new-vehicle'
    | '/categories/news'
    | '/categories/obtain-noc'
    | '/categories/other-state-vehicle'
    | '/categories/our-office'
    | '/categories/rto-list'
    | '/categories/rules'
    | '/categories/transfer-fees'
    | '/categories/transfer-ownership'
    | '/categories/used-vehicle-checklist'
    | '/categories/vehicle-safety'
    | '/admin'
    | '/admin/directory/create'
    | '/admin/directory/partener'
    | '/admin/directory'
    | '/admin/directory/$slug/details'
    | '/admin/directory/partner/$slug/details'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/association-events'
    | '/become-member'
    | '/contact'
    | '/directory'
    | '/image'
    | '/letter'
    | '/management'
    | '/political-achievements'
    | '/admin/banners'
    | '/admin/complaint'
    | '/admin/directory'
    | '/admin/enquiries'
    | '/admin/expired-members'
    | '/admin/image'
    | '/admin/important-dates'
    | '/admin/login'
    | '/admin/our-staff'
    | '/admin/reset-directory'
    | '/admin/reset-management'
    | '/admin/super-admins'
    | '/categories/authorized-dealers'
    | '/categories/duplicate-rc'
    | '/categories/emi-calculator'
    | '/categories/fees-structure'
    | '/categories/important-forms'
    | '/categories/information-on-forms'
    | '/categories/new-registrations'
    | '/categories/new-vehicle'
    | '/categories/news'
    | '/categories/obtain-noc'
    | '/categories/other-state-vehicle'
    | '/categories/our-office'
    | '/categories/rto-list'
    | '/categories/rules'
    | '/categories/transfer-fees'
    | '/categories/transfer-ownership'
    | '/categories/used-vehicle-checklist'
    | '/categories/vehicle-safety'
    | '/admin/'
    | '/admin/directory/create'
    | '/admin/directory/partener'
    | '/admin/directory/'
    | '/admin/directory/$slug/details'
    | '/admin/directory/partner/$slug/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssociationEventsRoute: typeof AssociationEventsRoute
  BecomeMemberRoute: typeof BecomeMemberRoute
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  ImageRoute: typeof ImageRoute
  LetterRoute: typeof LetterRoute
  ManagementRoute: typeof ManagementRoute
  PoliticalAchievementsRoute: typeof PoliticalAchievementsRoute
  CategoriesAuthorizedDealersRoute: typeof CategoriesAuthorizedDealersRoute
  CategoriesDuplicateRcRoute: typeof CategoriesDuplicateRcRoute
  CategoriesEmiCalculatorRoute: typeof CategoriesEmiCalculatorRoute
  CategoriesFeesStructureRoute: typeof CategoriesFeesStructureRoute
  CategoriesImportantFormsRoute: typeof CategoriesImportantFormsRoute
  CategoriesInformationOnFormsRoute: typeof CategoriesInformationOnFormsRoute
  CategoriesNewRegistrationsRoute: typeof CategoriesNewRegistrationsRoute
  CategoriesNewVehicleRoute: typeof CategoriesNewVehicleRoute
  CategoriesNewsRoute: typeof CategoriesNewsRoute
  CategoriesObtainNocRoute: typeof CategoriesObtainNocRoute
  CategoriesOtherStateVehicleRoute: typeof CategoriesOtherStateVehicleRoute
  CategoriesOurOfficeRoute: typeof CategoriesOurOfficeRoute
  CategoriesRtoListRoute: typeof CategoriesRtoListRoute
  CategoriesRulesRoute: typeof CategoriesRulesRoute
  CategoriesTransferFeesRoute: typeof CategoriesTransferFeesRoute
  CategoriesTransferOwnershipRoute: typeof CategoriesTransferOwnershipRoute
  CategoriesUsedVehicleChecklistRoute: typeof CategoriesUsedVehicleChecklistRoute
  CategoriesVehicleSafetyRoute: typeof CategoriesVehicleSafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/political-achievements': {
      id: '/political-achievements'
      path: '/political-achievements'
      fullPath: '/political-achievements'
      preLoaderRoute: typeof PoliticalAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-member': {
      id: '/become-member'
      path: '/become-member'
      fullPath: '/become-member'
      preLoaderRoute: typeof BecomeMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/association-events': {
      id: '/association-events'
      path: '/association-events'
      fullPath: '/association-events'
      preLoaderRoute: typeof AssociationEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/categories/vehicle-safety': {
      id: '/categories/vehicle-safety'
      path: '/categories/vehicle-safety'
      fullPath: '/categories/vehicle-safety'
      preLoaderRoute: typeof CategoriesVehicleSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/used-vehicle-checklist': {
      id: '/categories/used-vehicle-checklist'
      path: '/categories/used-vehicle-checklist'
      fullPath: '/categories/used-vehicle-checklist'
      preLoaderRoute: typeof CategoriesUsedVehicleChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/transfer-ownership': {
      id: '/categories/transfer-ownership'
      path: '/categories/transfer-ownership'
      fullPath: '/categories/transfer-ownership'
      preLoaderRoute: typeof CategoriesTransferOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/transfer-fees': {
      id: '/categories/transfer-fees'
      path: '/categories/transfer-fees'
      fullPath: '/categories/transfer-fees'
      preLoaderRoute: typeof CategoriesTransferFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/rules': {
      id: '/categories/rules'
      path: '/categories/rules'
      fullPath: '/categories/rules'
      preLoaderRoute: typeof CategoriesRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/rto-list': {
      id: '/categories/rto-list'
      path: '/categories/rto-list'
      fullPath: '/categories/rto-list'
      preLoaderRoute: typeof CategoriesRtoListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/our-office': {
      id: '/categories/our-office'
      path: '/categories/our-office'
      fullPath: '/categories/our-office'
      preLoaderRoute: typeof CategoriesOurOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/other-state-vehicle': {
      id: '/categories/other-state-vehicle'
      path: '/categories/other-state-vehicle'
      fullPath: '/categories/other-state-vehicle'
      preLoaderRoute: typeof CategoriesOtherStateVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/obtain-noc': {
      id: '/categories/obtain-noc'
      path: '/categories/obtain-noc'
      fullPath: '/categories/obtain-noc'
      preLoaderRoute: typeof CategoriesObtainNocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/news': {
      id: '/categories/news'
      path: '/categories/news'
      fullPath: '/categories/news'
      preLoaderRoute: typeof CategoriesNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/new-vehicle': {
      id: '/categories/new-vehicle'
      path: '/categories/new-vehicle'
      fullPath: '/categories/new-vehicle'
      preLoaderRoute: typeof CategoriesNewVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/new-registrations': {
      id: '/categories/new-registrations'
      path: '/categories/new-registrations'
      fullPath: '/categories/new-registrations'
      preLoaderRoute: typeof CategoriesNewRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/information-on-forms': {
      id: '/categories/information-on-forms'
      path: '/categories/information-on-forms'
      fullPath: '/categories/information-on-forms'
      preLoaderRoute: typeof CategoriesInformationOnFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/important-forms': {
      id: '/categories/important-forms'
      path: '/categories/important-forms'
      fullPath: '/categories/important-forms'
      preLoaderRoute: typeof CategoriesImportantFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/fees-structure': {
      id: '/categories/fees-structure'
      path: '/categories/fees-structure'
      fullPath: '/categories/fees-structure'
      preLoaderRoute: typeof CategoriesFeesStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/emi-calculator': {
      id: '/categories/emi-calculator'
      path: '/categories/emi-calculator'
      fullPath: '/categories/emi-calculator'
      preLoaderRoute: typeof CategoriesEmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/duplicate-rc': {
      id: '/categories/duplicate-rc'
      path: '/categories/duplicate-rc'
      fullPath: '/categories/duplicate-rc'
      preLoaderRoute: typeof CategoriesDuplicateRcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/authorized-dealers': {
      id: '/categories/authorized-dealers'
      path: '/categories/authorized-dealers'
      fullPath: '/categories/authorized-dealers'
      preLoaderRoute: typeof CategoriesAuthorizedDealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/super-admins': {
      id: '/admin/super-admins'
      path: '/super-admins'
      fullPath: '/admin/super-admins'
      preLoaderRoute: typeof AdminSuperAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-management': {
      id: '/admin/reset-management'
      path: '/reset-management'
      fullPath: '/admin/reset-management'
      preLoaderRoute: typeof AdminResetManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-directory': {
      id: '/admin/reset-directory'
      path: '/reset-directory'
      fullPath: '/admin/reset-directory'
      preLoaderRoute: typeof AdminResetDirectoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/our-staff': {
      id: '/admin/our-staff'
      path: '/our-staff'
      fullPath: '/admin/our-staff'
      preLoaderRoute: typeof AdminOurStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/important-dates': {
      id: '/admin/important-dates'
      path: '/important-dates'
      fullPath: '/admin/important-dates'
      preLoaderRoute: typeof AdminImportantDatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/image': {
      id: '/admin/image'
      path: '/image'
      fullPath: '/admin/image'
      preLoaderRoute: typeof AdminImageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expired-members': {
      id: '/admin/expired-members'
      path: '/expired-members'
      fullPath: '/admin/expired-members'
      preLoaderRoute: typeof AdminExpiredMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/directory': {
      id: '/admin/directory'
      path: '/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaint': {
      id: '/admin/complaint'
      path: '/complaint'
      fullPath: '/admin/complaint'
      preLoaderRoute: typeof AdminComplaintRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/directory/': {
      id: '/admin/directory/'
      path: '/'
      fullPath: '/admin/directory/'
      preLoaderRoute: typeof AdminDirectoryIndexRouteImport
      parentRoute: typeof AdminDirectoryRoute
    }
    '/admin/directory/partener': {
      id: '/admin/directory/partener'
      path: '/partener'
      fullPath: '/admin/directory/partener'
      preLoaderRoute: typeof AdminDirectoryPartenerRouteImport
      parentRoute: typeof AdminDirectoryRoute
    }
    '/admin/directory/create': {
      id: '/admin/directory/create'
      path: '/create'
      fullPath: '/admin/directory/create'
      preLoaderRoute: typeof AdminDirectoryCreateRouteImport
      parentRoute: typeof AdminDirectoryRoute
    }
    '/admin/directory/$slug/details': {
      id: '/admin/directory/$slug/details'
      path: '/$slug/details'
      fullPath: '/admin/directory/$slug/details'
      preLoaderRoute: typeof AdminDirectorySlugDetailsRouteImport
      parentRoute: typeof AdminDirectoryRoute
    }
    '/admin/directory/partner/$slug/details': {
      id: '/admin/directory/partner/$slug/details'
      path: '/partner/$slug/details'
      fullPath: '/admin/directory/partner/$slug/details'
      preLoaderRoute: typeof AdminDirectoryPartnerSlugDetailsRouteImport
      parentRoute: typeof AdminDirectoryRoute
    }
  }
}

interface AdminDirectoryRouteChildren {
  AdminDirectoryCreateRoute: typeof AdminDirectoryCreateRoute
  AdminDirectoryPartenerRoute: typeof AdminDirectoryPartenerRoute
  AdminDirectoryIndexRoute: typeof AdminDirectoryIndexRoute
  AdminDirectorySlugDetailsRoute: typeof AdminDirectorySlugDetailsRoute
  AdminDirectoryPartnerSlugDetailsRoute: typeof AdminDirectoryPartnerSlugDetailsRoute
}

const AdminDirectoryRouteChildren: AdminDirectoryRouteChildren = {
  AdminDirectoryCreateRoute: AdminDirectoryCreateRoute,
  AdminDirectoryPartenerRoute: AdminDirectoryPartenerRoute,
  AdminDirectoryIndexRoute: AdminDirectoryIndexRoute,
  AdminDirectorySlugDetailsRoute: AdminDirectorySlugDetailsRoute,
  AdminDirectoryPartnerSlugDetailsRoute: AdminDirectoryPartnerSlugDetailsRoute,
}

const AdminDirectoryRouteWithChildren = AdminDirectoryRoute._addFileChildren(
  AdminDirectoryRouteChildren,
)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminComplaintRoute: typeof AdminComplaintRoute
  AdminDirectoryRoute: typeof AdminDirectoryRouteWithChildren
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminExpiredMembersRoute: typeof AdminExpiredMembersRoute
  AdminImageRoute: typeof AdminImageRoute
  AdminImportantDatesRoute: typeof AdminImportantDatesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOurStaffRoute: typeof AdminOurStaffRoute
  AdminResetDirectoryRoute: typeof AdminResetDirectoryRoute
  AdminResetManagementRoute: typeof AdminResetManagementRoute
  AdminSuperAdminsRoute: typeof AdminSuperAdminsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminComplaintRoute: AdminComplaintRoute,
  AdminDirectoryRoute: AdminDirectoryRouteWithChildren,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminExpiredMembersRoute: AdminExpiredMembersRoute,
  AdminImageRoute: AdminImageRoute,
  AdminImportantDatesRoute: AdminImportantDatesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOurStaffRoute: AdminOurStaffRoute,
  AdminResetDirectoryRoute: AdminResetDirectoryRoute,
  AdminResetManagementRoute: AdminResetManagementRoute,
  AdminSuperAdminsRoute: AdminSuperAdminsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AssociationEventsRoute: AssociationEventsRoute,
  BecomeMemberRoute: BecomeMemberRoute,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  ImageRoute: ImageRoute,
  LetterRoute: LetterRoute,
  ManagementRoute: ManagementRoute,
  PoliticalAchievementsRoute: PoliticalAchievementsRoute,
  CategoriesAuthorizedDealersRoute: CategoriesAuthorizedDealersRoute,
  CategoriesDuplicateRcRoute: CategoriesDuplicateRcRoute,
  CategoriesEmiCalculatorRoute: CategoriesEmiCalculatorRoute,
  CategoriesFeesStructureRoute: CategoriesFeesStructureRoute,
  CategoriesImportantFormsRoute: CategoriesImportantFormsRoute,
  CategoriesInformationOnFormsRoute: CategoriesInformationOnFormsRoute,
  CategoriesNewRegistrationsRoute: CategoriesNewRegistrationsRoute,
  CategoriesNewVehicleRoute: CategoriesNewVehicleRoute,
  CategoriesNewsRoute: CategoriesNewsRoute,
  CategoriesObtainNocRoute: CategoriesObtainNocRoute,
  CategoriesOtherStateVehicleRoute: CategoriesOtherStateVehicleRoute,
  CategoriesOurOfficeRoute: CategoriesOurOfficeRoute,
  CategoriesRtoListRoute: CategoriesRtoListRoute,
  CategoriesRulesRoute: CategoriesRulesRoute,
  CategoriesTransferFeesRoute: CategoriesTransferFeesRoute,
  CategoriesTransferOwnershipRoute: CategoriesTransferOwnershipRoute,
  CategoriesUsedVehicleChecklistRoute: CategoriesUsedVehicleChecklistRoute,
  CategoriesVehicleSafetyRoute: CategoriesVehicleSafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.js'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
