/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticalAchievementsRouteImport } from './routes/political-achievements'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as LetterRouteImport } from './routes/letter'
import { Route as ImageRouteImport } from './routes/image'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssociationEventsRouteImport } from './routes/association-events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesVehicleSafetyRouteImport } from './routes/categories.vehicle-safety'
import { Route as CategoriesUsedVehicleChecklistRouteImport } from './routes/categories.used-vehicle-checklist'
import { Route as CategoriesTransferOwnershipRouteImport } from './routes/categories.transfer-ownership'
import { Route as CategoriesTransferFeesRouteImport } from './routes/categories.transfer-fees'
import { Route as CategoriesRulesRouteImport } from './routes/categories.rules'
import { Route as CategoriesRtoListRouteImport } from './routes/categories.rto-list'
import { Route as CategoriesOurOfficeRouteImport } from './routes/categories.our-office'
import { Route as CategoriesOtherStateVehicleRouteImport } from './routes/categories.other-state-vehicle'
import { Route as CategoriesObtainNocRouteImport } from './routes/categories.obtain-noc'
import { Route as CategoriesNewsRouteImport } from './routes/categories.news'
import { Route as CategoriesNewVehicleRouteImport } from './routes/categories.new-vehicle'
import { Route as CategoriesNewRegistrationsRouteImport } from './routes/categories.new-registrations'
import { Route as CategoriesInformationOnFormsRouteImport } from './routes/categories.information-on-forms'
import { Route as CategoriesImportantFormsRouteImport } from './routes/categories.important-forms'
import { Route as CategoriesFeesStructureRouteImport } from './routes/categories.fees-structure'
import { Route as CategoriesEmiCalculatorRouteImport } from './routes/categories.emi-calculator'
import { Route as CategoriesDuplicateRcRouteImport } from './routes/categories.duplicate-rc'
import { Route as CategoriesAuthorizedDealersRouteImport } from './routes/categories.authorized-dealers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const PoliticalAchievementsRoute = PoliticalAchievementsRouteImport.update({
  id: '/political-achievements',
  path: '/political-achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const LetterRoute = LetterRouteImport.update({
  id: '/letter',
  path: '/letter',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationEventsRoute = AssociationEventsRouteImport.update({
  id: '/association-events',
  path: '/association-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesVehicleSafetyRoute = CategoriesVehicleSafetyRouteImport.update({
  id: '/categories/vehicle-safety',
  path: '/categories/vehicle-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesUsedVehicleChecklistRoute =
  CategoriesUsedVehicleChecklistRouteImport.update({
    id: '/categories/used-vehicle-checklist',
    path: '/categories/used-vehicle-checklist',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesTransferOwnershipRoute =
  CategoriesTransferOwnershipRouteImport.update({
    id: '/categories/transfer-ownership',
    path: '/categories/transfer-ownership',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesTransferFeesRoute = CategoriesTransferFeesRouteImport.update({
  id: '/categories/transfer-fees',
  path: '/categories/transfer-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRulesRoute = CategoriesRulesRouteImport.update({
  id: '/categories/rules',
  path: '/categories/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRtoListRoute = CategoriesRtoListRouteImport.update({
  id: '/categories/rto-list',
  path: '/categories/rto-list',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesOurOfficeRoute = CategoriesOurOfficeRouteImport.update({
  id: '/categories/our-office',
  path: '/categories/our-office',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesOtherStateVehicleRoute =
  CategoriesOtherStateVehicleRouteImport.update({
    id: '/categories/other-state-vehicle',
    path: '/categories/other-state-vehicle',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesObtainNocRoute = CategoriesObtainNocRouteImport.update({
  id: '/categories/obtain-noc',
  path: '/categories/obtain-noc',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewsRoute = CategoriesNewsRouteImport.update({
  id: '/categories/news',
  path: '/categories/news',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewVehicleRoute = CategoriesNewVehicleRouteImport.update({
  id: '/categories/new-vehicle',
  path: '/categories/new-vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewRegistrationsRoute =
  CategoriesNewRegistrationsRouteImport.update({
    id: '/categories/new-registrations',
    path: '/categories/new-registrations',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesInformationOnFormsRoute =
  CategoriesInformationOnFormsRouteImport.update({
    id: '/categories/information-on-forms',
    path: '/categories/information-on-forms',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesImportantFormsRoute =
  CategoriesImportantFormsRouteImport.update({
    id: '/categories/important-forms',
    path: '/categories/important-forms',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategoriesFeesStructureRoute = CategoriesFeesStructureRouteImport.update({
  id: '/categories/fees-structure',
  path: '/categories/fees-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesEmiCalculatorRoute = CategoriesEmiCalculatorRouteImport.update({
  id: '/categories/emi-calculator',
  path: '/categories/emi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesDuplicateRcRoute = CategoriesDuplicateRcRouteImport.update({
  id: '/categories/duplicate-rc',
  path: '/categories/duplicate-rc',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesAuthorizedDealersRoute =
  CategoriesAuthorizedDealersRouteImport.update({
    id: '/categories/authorized-dealers',
    path: '/categories/authorized-dealers',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/association-events': typeof AssociationEventsRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/image': typeof ImageRoute
  '/letter': typeof LetterRoute
  '/management': typeof ManagementRoute
  '/political-achievements': typeof PoliticalAchievementsRoute
  '/admin/login': typeof AdminLoginRoute
  '/categories/authorized-dealers': typeof CategoriesAuthorizedDealersRoute
  '/categories/duplicate-rc': typeof CategoriesDuplicateRcRoute
  '/categories/emi-calculator': typeof CategoriesEmiCalculatorRoute
  '/categories/fees-structure': typeof CategoriesFeesStructureRoute
  '/categories/important-forms': typeof CategoriesImportantFormsRoute
  '/categories/information-on-forms': typeof CategoriesInformationOnFormsRoute
  '/categories/new-registrations': typeof CategoriesNewRegistrationsRoute
  '/categories/new-vehicle': typeof CategoriesNewVehicleRoute
  '/categories/news': typeof CategoriesNewsRoute
  '/categories/obtain-noc': typeof CategoriesObtainNocRoute
  '/categories/other-state-vehicle': typeof CategoriesOtherStateVehicleRoute
  '/categories/our-office': typeof CategoriesOurOfficeRoute
  '/categories/rto-list': typeof CategoriesRtoListRoute
  '/categories/rules': typeof CategoriesRulesRoute
  '/categories/transfer-fees': typeof CategoriesTransferFeesRoute
  '/categories/transfer-ownership': typeof CategoriesTransferOwnershipRoute
  '/categories/used-vehicle-checklist': typeof CategoriesUsedVehicleChecklistRoute
  '/categories/vehicle-safety': typeof CategoriesVehicleSafetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/association-events': typeof AssociationEventsRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/image': typeof ImageRoute
  '/letter': typeof LetterRoute
  '/management': typeof ManagementRoute
  '/political-achievements': typeof PoliticalAchievementsRoute
  '/admin/login': typeof AdminLoginRoute
  '/categories/authorized-dealers': typeof CategoriesAuthorizedDealersRoute
  '/categories/duplicate-rc': typeof CategoriesDuplicateRcRoute
  '/categories/emi-calculator': typeof CategoriesEmiCalculatorRoute
  '/categories/fees-structure': typeof CategoriesFeesStructureRoute
  '/categories/important-forms': typeof CategoriesImportantFormsRoute
  '/categories/information-on-forms': typeof CategoriesInformationOnFormsRoute
  '/categories/new-registrations': typeof CategoriesNewRegistrationsRoute
  '/categories/new-vehicle': typeof CategoriesNewVehicleRoute
  '/categories/news': typeof CategoriesNewsRoute
  '/categories/obtain-noc': typeof CategoriesObtainNocRoute
  '/categories/other-state-vehicle': typeof CategoriesOtherStateVehicleRoute
  '/categories/our-office': typeof CategoriesOurOfficeRoute
  '/categories/rto-list': typeof CategoriesRtoListRoute
  '/categories/rules': typeof CategoriesRulesRoute
  '/categories/transfer-fees': typeof CategoriesTransferFeesRoute
  '/categories/transfer-ownership': typeof CategoriesTransferOwnershipRoute
  '/categories/used-vehicle-checklist': typeof CategoriesUsedVehicleChecklistRoute
  '/categories/vehicle-safety': typeof CategoriesVehicleSafetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/association-events': typeof AssociationEventsRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/image': typeof ImageRoute
  '/letter': typeof LetterRoute
  '/management': typeof ManagementRoute
  '/political-achievements': typeof PoliticalAchievementsRoute
  '/admin/login': typeof AdminLoginRoute
  '/categories/authorized-dealers': typeof CategoriesAuthorizedDealersRoute
  '/categories/duplicate-rc': typeof CategoriesDuplicateRcRoute
  '/categories/emi-calculator': typeof CategoriesEmiCalculatorRoute
  '/categories/fees-structure': typeof CategoriesFeesStructureRoute
  '/categories/important-forms': typeof CategoriesImportantFormsRoute
  '/categories/information-on-forms': typeof CategoriesInformationOnFormsRoute
  '/categories/new-registrations': typeof CategoriesNewRegistrationsRoute
  '/categories/new-vehicle': typeof CategoriesNewVehicleRoute
  '/categories/news': typeof CategoriesNewsRoute
  '/categories/obtain-noc': typeof CategoriesObtainNocRoute
  '/categories/other-state-vehicle': typeof CategoriesOtherStateVehicleRoute
  '/categories/our-office': typeof CategoriesOurOfficeRoute
  '/categories/rto-list': typeof CategoriesRtoListRoute
  '/categories/rules': typeof CategoriesRulesRoute
  '/categories/transfer-fees': typeof CategoriesTransferFeesRoute
  '/categories/transfer-ownership': typeof CategoriesTransferOwnershipRoute
  '/categories/used-vehicle-checklist': typeof CategoriesUsedVehicleChecklistRoute
  '/categories/vehicle-safety': typeof CategoriesVehicleSafetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/association-events'
    | '/contact'
    | '/directory'
    | '/image'
    | '/letter'
    | '/management'
    | '/political-achievements'
    | '/admin/login'
    | '/categories/authorized-dealers'
    | '/categories/duplicate-rc'
    | '/categories/emi-calculator'
    | '/categories/fees-structure'
    | '/categories/important-forms'
    | '/categories/information-on-forms'
    | '/categories/new-registrations'
    | '/categories/new-vehicle'
    | '/categories/news'
    | '/categories/obtain-noc'
    | '/categories/other-state-vehicle'
    | '/categories/our-office'
    | '/categories/rto-list'
    | '/categories/rules'
    | '/categories/transfer-fees'
    | '/categories/transfer-ownership'
    | '/categories/used-vehicle-checklist'
    | '/categories/vehicle-safety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/association-events'
    | '/contact'
    | '/directory'
    | '/image'
    | '/letter'
    | '/management'
    | '/political-achievements'
    | '/admin/login'
    | '/categories/authorized-dealers'
    | '/categories/duplicate-rc'
    | '/categories/emi-calculator'
    | '/categories/fees-structure'
    | '/categories/important-forms'
    | '/categories/information-on-forms'
    | '/categories/new-registrations'
    | '/categories/new-vehicle'
    | '/categories/news'
    | '/categories/obtain-noc'
    | '/categories/other-state-vehicle'
    | '/categories/our-office'
    | '/categories/rto-list'
    | '/categories/rules'
    | '/categories/transfer-fees'
    | '/categories/transfer-ownership'
    | '/categories/used-vehicle-checklist'
    | '/categories/vehicle-safety'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/association-events'
    | '/contact'
    | '/directory'
    | '/image'
    | '/letter'
    | '/management'
    | '/political-achievements'
    | '/admin/login'
    | '/categories/authorized-dealers'
    | '/categories/duplicate-rc'
    | '/categories/emi-calculator'
    | '/categories/fees-structure'
    | '/categories/important-forms'
    | '/categories/information-on-forms'
    | '/categories/new-registrations'
    | '/categories/new-vehicle'
    | '/categories/news'
    | '/categories/obtain-noc'
    | '/categories/other-state-vehicle'
    | '/categories/our-office'
    | '/categories/rto-list'
    | '/categories/rules'
    | '/categories/transfer-fees'
    | '/categories/transfer-ownership'
    | '/categories/used-vehicle-checklist'
    | '/categories/vehicle-safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssociationEventsRoute: typeof AssociationEventsRoute
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  ImageRoute: typeof ImageRoute
  LetterRoute: typeof LetterRoute
  ManagementRoute: typeof ManagementRoute
  PoliticalAchievementsRoute: typeof PoliticalAchievementsRoute
  CategoriesAuthorizedDealersRoute: typeof CategoriesAuthorizedDealersRoute
  CategoriesDuplicateRcRoute: typeof CategoriesDuplicateRcRoute
  CategoriesEmiCalculatorRoute: typeof CategoriesEmiCalculatorRoute
  CategoriesFeesStructureRoute: typeof CategoriesFeesStructureRoute
  CategoriesImportantFormsRoute: typeof CategoriesImportantFormsRoute
  CategoriesInformationOnFormsRoute: typeof CategoriesInformationOnFormsRoute
  CategoriesNewRegistrationsRoute: typeof CategoriesNewRegistrationsRoute
  CategoriesNewVehicleRoute: typeof CategoriesNewVehicleRoute
  CategoriesNewsRoute: typeof CategoriesNewsRoute
  CategoriesObtainNocRoute: typeof CategoriesObtainNocRoute
  CategoriesOtherStateVehicleRoute: typeof CategoriesOtherStateVehicleRoute
  CategoriesOurOfficeRoute: typeof CategoriesOurOfficeRoute
  CategoriesRtoListRoute: typeof CategoriesRtoListRoute
  CategoriesRulesRoute: typeof CategoriesRulesRoute
  CategoriesTransferFeesRoute: typeof CategoriesTransferFeesRoute
  CategoriesTransferOwnershipRoute: typeof CategoriesTransferOwnershipRoute
  CategoriesUsedVehicleChecklistRoute: typeof CategoriesUsedVehicleChecklistRoute
  CategoriesVehicleSafetyRoute: typeof CategoriesVehicleSafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/political-achievements': {
      id: '/political-achievements'
      path: '/political-achievements'
      fullPath: '/political-achievements'
      preLoaderRoute: typeof PoliticalAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letter': {
      id: '/letter'
      path: '/letter'
      fullPath: '/letter'
      preLoaderRoute: typeof LetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/association-events': {
      id: '/association-events'
      path: '/association-events'
      fullPath: '/association-events'
      preLoaderRoute: typeof AssociationEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/vehicle-safety': {
      id: '/categories/vehicle-safety'
      path: '/categories/vehicle-safety'
      fullPath: '/categories/vehicle-safety'
      preLoaderRoute: typeof CategoriesVehicleSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/used-vehicle-checklist': {
      id: '/categories/used-vehicle-checklist'
      path: '/categories/used-vehicle-checklist'
      fullPath: '/categories/used-vehicle-checklist'
      preLoaderRoute: typeof CategoriesUsedVehicleChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/transfer-ownership': {
      id: '/categories/transfer-ownership'
      path: '/categories/transfer-ownership'
      fullPath: '/categories/transfer-ownership'
      preLoaderRoute: typeof CategoriesTransferOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/transfer-fees': {
      id: '/categories/transfer-fees'
      path: '/categories/transfer-fees'
      fullPath: '/categories/transfer-fees'
      preLoaderRoute: typeof CategoriesTransferFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/rules': {
      id: '/categories/rules'
      path: '/categories/rules'
      fullPath: '/categories/rules'
      preLoaderRoute: typeof CategoriesRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/rto-list': {
      id: '/categories/rto-list'
      path: '/categories/rto-list'
      fullPath: '/categories/rto-list'
      preLoaderRoute: typeof CategoriesRtoListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/our-office': {
      id: '/categories/our-office'
      path: '/categories/our-office'
      fullPath: '/categories/our-office'
      preLoaderRoute: typeof CategoriesOurOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/other-state-vehicle': {
      id: '/categories/other-state-vehicle'
      path: '/categories/other-state-vehicle'
      fullPath: '/categories/other-state-vehicle'
      preLoaderRoute: typeof CategoriesOtherStateVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/obtain-noc': {
      id: '/categories/obtain-noc'
      path: '/categories/obtain-noc'
      fullPath: '/categories/obtain-noc'
      preLoaderRoute: typeof CategoriesObtainNocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/news': {
      id: '/categories/news'
      path: '/categories/news'
      fullPath: '/categories/news'
      preLoaderRoute: typeof CategoriesNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/new-vehicle': {
      id: '/categories/new-vehicle'
      path: '/categories/new-vehicle'
      fullPath: '/categories/new-vehicle'
      preLoaderRoute: typeof CategoriesNewVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/new-registrations': {
      id: '/categories/new-registrations'
      path: '/categories/new-registrations'
      fullPath: '/categories/new-registrations'
      preLoaderRoute: typeof CategoriesNewRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/information-on-forms': {
      id: '/categories/information-on-forms'
      path: '/categories/information-on-forms'
      fullPath: '/categories/information-on-forms'
      preLoaderRoute: typeof CategoriesInformationOnFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/important-forms': {
      id: '/categories/important-forms'
      path: '/categories/important-forms'
      fullPath: '/categories/important-forms'
      preLoaderRoute: typeof CategoriesImportantFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/fees-structure': {
      id: '/categories/fees-structure'
      path: '/categories/fees-structure'
      fullPath: '/categories/fees-structure'
      preLoaderRoute: typeof CategoriesFeesStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/emi-calculator': {
      id: '/categories/emi-calculator'
      path: '/categories/emi-calculator'
      fullPath: '/categories/emi-calculator'
      preLoaderRoute: typeof CategoriesEmiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/duplicate-rc': {
      id: '/categories/duplicate-rc'
      path: '/categories/duplicate-rc'
      fullPath: '/categories/duplicate-rc'
      preLoaderRoute: typeof CategoriesDuplicateRcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/authorized-dealers': {
      id: '/categories/authorized-dealers'
      path: '/categories/authorized-dealers'
      fullPath: '/categories/authorized-dealers'
      preLoaderRoute: typeof CategoriesAuthorizedDealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AssociationEventsRoute: AssociationEventsRoute,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  ImageRoute: ImageRoute,
  LetterRoute: LetterRoute,
  ManagementRoute: ManagementRoute,
  PoliticalAchievementsRoute: PoliticalAchievementsRoute,
  CategoriesAuthorizedDealersRoute: CategoriesAuthorizedDealersRoute,
  CategoriesDuplicateRcRoute: CategoriesDuplicateRcRoute,
  CategoriesEmiCalculatorRoute: CategoriesEmiCalculatorRoute,
  CategoriesFeesStructureRoute: CategoriesFeesStructureRoute,
  CategoriesImportantFormsRoute: CategoriesImportantFormsRoute,
  CategoriesInformationOnFormsRoute: CategoriesInformationOnFormsRoute,
  CategoriesNewRegistrationsRoute: CategoriesNewRegistrationsRoute,
  CategoriesNewVehicleRoute: CategoriesNewVehicleRoute,
  CategoriesNewsRoute: CategoriesNewsRoute,
  CategoriesObtainNocRoute: CategoriesObtainNocRoute,
  CategoriesOtherStateVehicleRoute: CategoriesOtherStateVehicleRoute,
  CategoriesOurOfficeRoute: CategoriesOurOfficeRoute,
  CategoriesRtoListRoute: CategoriesRtoListRoute,
  CategoriesRulesRoute: CategoriesRulesRoute,
  CategoriesTransferFeesRoute: CategoriesTransferFeesRoute,
  CategoriesTransferOwnershipRoute: CategoriesTransferOwnershipRoute,
  CategoriesUsedVehicleChecklistRoute: CategoriesUsedVehicleChecklistRoute,
  CategoriesVehicleSafetyRoute: CategoriesVehicleSafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.js'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
